### ISSUE TITLE
Project Scope Approval 

### ISSUE THREAD

**Issue by KateMShirley** [wdi-clydesdale/alemanac#1]
Summary: Tentatively named 'Point of Brew', this app will have both beer search functionality and CRUD functionality within a 'beer journal'.

User Flow: Users are first prompted to login, once they've logged in they are taken to a page where than can either choose to search, choose to go to their journal page, or choose to edit/view a beer that they've previously logged. The search functionality will be provided by the Brewery DB API and users will be able to search by a pre-defined set of parameters. The journal functionality will be created using SQL/ActiveRecord and users will be able to save beers that they've tried with notes and ratings.

Technologies:
-Ruby
-SQL
-ActiveRecord
-Bootstrap

Views:

Age Confirmation
login
search/Search Results
myBeers
myBeers entry
Edit entries

Models:

Users
Beers

Controllers:
Home
Users
Beers

Blockers/things to discuss in 1 on 1:
-using/storing img in database
-using the API
-how to append the key to our API calls

Goals:
-Day 1:
    -Wireframes/Userstories
    -Plan out API/Database structure
    -Skeleton structure of files/models/controllers

**Comment by code-for-coffee** [comment]
@KateMShirley @davidlhayes this'll be a lot of fun! The ability to add a beer is awesome. I like how easy the interface is for users, too. 

Note: Add boolean column to beer table to specify if a beer is custom added or not.

Legally you must require users are 21+ in the US, fyi. https://en.wikipedia.org/wiki/National_Minimum_Drinking_Age_Act

Approved!
